baseURL = "https://zhurongshuo.com/"
publishDir= "docs"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "祝融说。"
theme = "zozo"
hasCJKLanguage = true
summaryLength = 120
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[pagination]
  pagerSize = 10

[author]
  name = "祝融"

[blackfriday]
  smartypants = false

[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "开始"
  weight = 20
  identifier = "start"
  url = "/start/"
[[menu.main]]
  name = "进阶"
  weight = 25
  identifier = "advanced"
  url = "/advanced/"
[[menu.main]]
  name = "归档"
  weight = 30
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "法不净空，觉无性也。"
  footerSlogan = "法不净空，觉无性也。"
  keywords = ["祝融", "祝融说"]
  description = "祝融说：法不净空，觉无性也。"
  copyrights = "Copyright © 2010-2025 祝融说 zhurongshuo.com All Rights Reserved."
  enableMathJax = true
  enableSummary = true
  mainSections = ["posts", "post"]

[params.author]
  name = "祝融"

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[params.social]
  game = "/about/"
  book-open = "/books/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = ""
  filename = "sitemap.xml"
  priority = -1
