name = "image-resizer"
main = "workers/image-resizer.js"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
route = "r2.zhurongshuo.com/*"

# R2 bucket binding for production
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "zhurongshuo"
